#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
# see c++ implementation for more methods
def findTheDifference(s, t):
	for c in set(t):
		if s.count(c) != t.count(c):
			return c
	
s = "abcd"
t = "abcde"
print findTheDifference(s, t)
print findTheDifference2(s, t)
