/*
 Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
*/
#include<iostream>
#include<string>
#include<map>
#include <algorithm>
//#include<cstring>
using namespace std;

char finddiff(string s, string t) // store string in the map <letter, count> then find 
{
	map<char, unsigned int> stringtable;
	// store string s into map
	for (int i = 0; i < s.size(); i++) 
	{
		auto pos = stringtable.find(s[i]);
		if (pos != stringtable.end()) // found the element then add 1
		{
			pos->second += 1;
		}
		else // not found create one element
		{
			stringtable.insert(pair <char, unsigned int>(s[i], 1));
		}
	}
	
	// find the difference in the map
	for (int i = 0; i < t.size(); i++) 
	{
		cout<<"finding "<<t[i]<<endl;
		auto pos = stringtable.find(t[i]);
		if (pos != stringtable.end()) // found the element
		{
			if (pos->second == 0)// this element is the difference
			{
				return pos->first;
			}
			else
			{
				pos->second -= 1; // minus 1
			}
		}
		else // element not in the map return it
		{
			return t[i];
		}
	}
	return 0;
}

char finddiff2(string s, string t) // find and delete
{
	for (int i = 0; i < s.size(); i++)
	{
		cout<<"finding "<<s[i]<<endl;
		size_t pos = t.find(s[i], 0);
		if (pos != string::npos) // found the element in t
			t.erase(pos, 1); // delete
	}
	char c = t[0]; // remaining last element
	return c;
}

char finddiff3(string s, string t) // using XOR
{
	string c = t + s;
	int ret = c[0];
	for (int i = 1; i < c.size(); i++)
	{
		ret = ret^c[i];
	}
	return char(ret);
}

char finddiff4(string s, string t) // sum(t)-sum(s)
{
	int sum = 0;
	for (int i = 0; i < t.size(); i++)
		sum += t[i];
	for (int i = 0; i < s.size(); i++)
		sum -= s[i];
	char ret = sum;
	return ret;
}

char finddiff5(string s, string t) // same to finddiff4, add & sub in the same loop
{
	int sum = 0;
	for (int i = 0; i < t.size(); i++)
	{
		sum += t[i];
		if (i == t.size()-1)
			continue;
		sum -= s[i];
	}
	char ret = sum;
	return ret;
}

char finddiff6(string s, string t) // sort and find the first diff
{
	sort(s.begin(), s.end());
	sort(t.begin(), t.end());
	for (int i = 0; i < s.size(); i++)
	{
		if (s[i] != t[i])
		{
			return s[i];
		}
	}
	return t[t.size() - 1];
}

int main()
{
	string s = "ymbgaraibkfmvocpizdydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmoswrcxnargtlswqemafandgkmydtimuzvjwxvlfwlhvkrgcsithaqlcvrihrwqkpjdhgfgreqoxzfvhjzojhghfwbvpfzectwwhexthbsndovxejsntmjihchaotbgcysfdaojkjldprwyrnischrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuinkyygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczcovrmwqxxbnhfzcjjcpgzjjfateajnnvlbwhyppdleahgaypxidkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjszolgwqvfiozofncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrrymrfdxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpqsspyssrmdhuelkkvyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxkvwkrwdcxjfzikdyswsuxegmhtnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfovaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrcwjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtelhwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdjkfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgddqwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor";
	string t = "qhxepbshlrhoecdaodgpousbzfcqjxulatciapuftffahhlmxbufgjuxstfjvljybfxnenlacmjqoymvamphpxnolwijwcecgwbcjhgdybfffwoygikvoecdggplfohemfypxfsvdrseyhmvkoovxhdvoavsqqbrsqrkqhbtmgwaurgisloqjixfwfvwtszcxwktkwesaxsmhsvlitegrlzkvfqoiiwxbzskzoewbkxtphapavbyvhzvgrrfriddnsrftfowhdanvhjvurhljmpxvpddxmzfgwwpkjrfgqptrmumoemhfpojnxzwlrxkcafvbhlwrapubhveattfifsmiounhqusvhywnxhwrgamgnesxmzliyzisqrwvkiyderyotxhwspqrrkeczjysfujvovsfcfouykcqyjoobfdgnlswfzjmyucaxuaslzwfnetekymrwbvponiaojdqnbmboldvvitamntwnyaeppjaohwkrisrlrgwcjqqgxeqerjrbapfzurcwxhcwzugcgnirkkrxdthtbmdqgvqxilllrsbwjhwqszrjtzyetwubdrlyakzxcveufvhqugyawvkivwonvmrgnchkzdysngqdibhkyboyftxcvvjoggecjsajbuqkjjxfvynrjsnvtfvgpgveycxidhhfauvjovmnbqgoxsafknluyimkczykwdgvqwlvvgdmufxdypwnajkncoynqticfetcdafvtqszuwfmrdggifokwmkgzuxnhncmnsstffqpqbplypapctctfhqpihavligbrutxmmygiyaklqtakdidvnvrjfteazeqmbgklrgrorudayokxptswwkcircwuhcavhdparjfkjypkyxhbgwxbkvpvrtzjaetahmxevmkhdfyidhrdeejapfbafwmdqjqszwnwzgclitdhlnkaiyldwkwwzvhyorgbysyjbxsspnjdewjxbhpsvj";
	
	//string s = "abecd", t = "abcede"; // "b" is added
	cout<<finddiff6(s, t)<<" is added."<<endl;
	return 0;
}
